window.TT_PRODUCTS = [
  { sku:'WOM-001', title:'Rose Knit Cardigan', category:'Women', subcategory:'Sweaters', audience:'Women', price:18, size:'M', brand:'A New Day', condition:'Gem Condition', status:'Available', description:'Soft neutral layering piece with a cozy drape for workdays or weekends.', image:'◇', hiddenGem:false, clearance:false },
  { sku:'WOM-002', title:'New With Tags Blouse', category:'Women', subcategory:'Tops', audience:'Women', price:15, size:'S', brand:'Loft', condition:'New With Tags', status:'Available', description:'Polished blouse with original tag attached and a clean closet-ready finish.', image:'✦', hiddenGem:false, clearance:false },
  { sku:'MEN-001', title:'Men’s Flannel Shirt', category:'Men', subcategory:'Shirts', audience:'Men', price:13, size:'XL', brand:'Wrangler', condition:'Great Condition', status:'Available', description:'Steamed, odor-checked flannel with an easy everyday fit.', image:'◇', hiddenGem:false, clearance:false },
  { sku:'LG-001', title:'Little Gems Pajama Set', category:'Little Gems', subcategory:'Sleepwear', audience:'Children', price:7, size:'4T', brand:'Carter’s', condition:'Good Condition', status:'Available', description:'Children’s pajama set reviewed for condition, folded, and ready for a new little gem.', image:'♡', hiddenGem:false, clearance:false },
  { sku:'SHOE-001', title:'Black Ankle Boots', category:'Shoes', subcategory:'Boots', audience:'Women', price:22, size:'8', brand:'Time and Tru', condition:'Great Condition', status:'Available', description:'Clean soles with minor creasing disclosed for confident browsing.', image:'◈', hiddenGem:false, clearance:false },
  { sku:'BAG-001', title:'Everyday Crossbody Bag', category:'Bags', subcategory:'Crossbody Bags', audience:'All', price:14, size:'OS', brand:'Mossimo', condition:'Good Condition', status:'Sold', description:'Light corner wear is disclosed on this compact hands-free bag.', image:'✧', hiddenGem:false, clearance:false },
  { sku:'ACC-001', title:'Amethyst Earring Set', category:'Accessories', subcategory:'Jewelry', audience:'All', price:6, size:'OS', brand:'Unbranded', condition:'New With Tags', status:'Available', description:'Carded accessory find with a polished purple sparkle.', image:'✶', hiddenGem:false, clearance:false },
  { sku:'HOME-001', title:'Pearl Ceramic Vase', category:'Home Treasures', subcategory:'Décor', audience:'Home', price:12, size:'Small', brand:'Unbranded', condition:'Gem Condition', status:'Available', description:'Small ceramic vase with a pearly finish and no chips or cracks.', image:'◇', hiddenGem:false, clearance:false },
  { sku:'HG-001', title:'Designer Silk Scarf', category:'Accessories', subcategory:'Scarves', audience:'All', price:34, size:'OS', brand:'Coach', condition:'Mint Condition', status:'Reserved', description:'Standout silk scarf selected for Hidden Gems feature placement.', image:'◆', hiddenGem:true, clearance:false },
  { sku:'CLR-001', title:'Last-Chance Soft Tee Bundle', category:'Women', subcategory:'Tops Bundle', audience:'Women', price:8, size:'M/L', brand:'Mixed', condition:'Good Condition', status:'Available', description:'Markdown bundle for budget-friendly everyday layering pieces.', image:'◇', hiddenGem:false, clearance:true }
];
