const products = window.TT_PRODUCTS || [];
const categories = ['All', ...new Set(products.map((p) => p.category))];
const bagKey = 'treasured-twice-request-bag';
const inventoryKey = 'treasured-twice-owner-inventory';
const donationKey = 'treasured-twice-donation-requests';
const contactKey = 'treasured-twice-contact-requests';
const emptyStateText = 'More treasures are being prepared. Check back soon or follow us for the next Hidden Gems Drop.';

function getBag(){ return JSON.parse(localStorage.getItem(bagKey) || '[]'); }
function setBag(items){ localStorage.setItem(bagKey, JSON.stringify(items)); updateBagCount(); }
function updateBagCount(){ document.querySelectorAll('[data-bag-count]').forEach((el)=>{ el.textContent = getBag().length; }); }
function money(v){ return `$${Number(v || 0).toFixed(2)}`; }
function normalizeItem(item){ return { ...item, image:item.image || item.photo || '◇', description:item.description || item.notes || '', subcategory:item.subcategory || 'Featured Find', audience:item.audience || 'All', hiddenGem:Boolean(item.hiddenGem), clearance:Boolean(item.clearance) }; }
function appProducts(){ return (JSON.parse(localStorage.getItem(inventoryKey) || 'null') || products).map(normalizeItem); }
function saveProducts(items){ localStorage.setItem(inventoryKey, JSON.stringify(items)); }
function requestItem(sku){ const item = appProducts().find((p)=>p.sku===sku); if(!item) return; const bag = getBag(); if(!bag.find((p)=>p.sku===sku)) bag.push(item); setBag(bag); alert(`${item.title} was added to your request bag preview.`); }
window.requestItem = requestItem;

function productCard(p){ const disabled = ['Sold','Reserved'].includes(p.status); return `<article class="product-card" data-category="${p.category}" data-subcategory="${p.subcategory}" data-status="${p.status}">
  <div class="product-photo" aria-label="Product image area">${p.image}</div>
  <div class="product-meta"><span>${p.sku}</span><span class="status ${String(p.status).toLowerCase()}">${p.status}</span></div>
  <h3><a href="product.html?sku=${encodeURIComponent(p.sku)}">${p.title}</a></h3>
  <p class="category-line">${p.category} / ${p.subcategory}</p>
  <dl><div><dt>Price</dt><dd>${money(p.price)}</dd></div><div><dt>Size</dt><dd>${p.size}</dd></div><div><dt>Brand</dt><dd>${p.brand}</dd></div><div><dt>Condition</dt><dd>${p.condition}</dd></div></dl>
  <p>${p.description}</p><button class="button primary compact" ${disabled?'disabled':''} onclick="requestItem('${p.sku}')">Add to Request Bag</button>
</article>`; }

function pageCategory(){ return document.body.dataset.category || document.querySelector('[data-page-category]')?.dataset.pageCategory || ''; }
function pageFlag(){ return document.querySelector('[data-page-filter]')?.dataset.pageFilter || ''; }
function filteredProducts(){ const search=document.querySelector('[data-search]'); const filter=document.querySelector('[data-filter]'); const q=(search?.value||'').toLowerCase(); const cat=filter?.value||'All'; const forced=pageCategory(); const flag=pageFlag(); return appProducts().filter((p)=>{
  const pageMatch = flag === 'hiddenGem' ? p.hiddenGem : flag === 'clearance' ? p.clearance : (!forced || p.category === forced);
  return pageMatch && (cat==='All'||p.category===cat) && [p.sku,p.title,p.category,p.subcategory,p.audience,p.brand,p.condition,p.status,p.description].join(' ').toLowerCase().includes(q);
}); }
function renderShop(){ const grid=document.querySelector('[data-product-grid]'); if(!grid) return; const filter=document.querySelector('[data-filter]'); if(filter && !filter.dataset.ready){ filter.innerHTML = categories.map((c)=>`<option>${c}</option>`).join(''); filter.dataset.ready='true'; } const filtered=filteredProducts(); grid.innerHTML=filtered.map(productCard).join('') || `<p class="empty-state">${emptyStateText}</p>`; }
function renderCategoryHub(){ const hub=document.querySelector('[data-category-hub]'); if(!hub) return; const cards=[['Women','women.html','Curated apparel and style finds.'],['Men','men.html','Everyday menswear and practical pieces.'],['Little Gems','little-gems.html','Children’s treasures newborn through size 12.'],['Shoes','shoes.html','Reviewed footwear with clear condition notes.'],['Bags','bags.html','Totes, crossbodies, wallets, and more.'],['Accessories','accessories.html','Jewelry, scarves, belts, and finishing touches.'],['Home Treasures','home-treasures.html','Décor, linens, kitchen finds, and small home goods.'],['Hidden Gems','hidden-gems.html','Featured standout items from the latest drop.'],['Clearance','clearance.html','Markdown, bundle, and last-chance items.']]; hub.innerHTML=cards.map(([title,href,copy])=>`<article><h3>${title}</h3><p>${copy}</p><a class="button secondary" href="${href}">Browse ${title}</a></article>`).join(''); }
function renderProductDetail(){ const el=document.querySelector('[data-product-detail]'); if(!el) return; const sku=new URLSearchParams(location.search).get('sku'); const item=appProducts().find(p=>p.sku===sku); el.innerHTML=item ? productCard(item) : '<p class="empty-state">This item is no longer available or could not be found.</p>'; }
function renderBag(){ const el=document.querySelector('[data-request-bag]'); if(!el) return; const bag=getBag(); el.innerHTML = bag.length ? bag.map((p)=>`<li>${p.sku} — ${p.title} <button data-remove="${p.sku}">Remove</button></li>`).join('') : '<li>Your saved request bag is empty.</li>'; el.querySelectorAll('[data-remove]').forEach((b)=>b.addEventListener('click',()=>{setBag(getBag().filter((p)=>p.sku!==b.dataset.remove)); renderBag();})); }

function renderAdmin(){ const cards=document.querySelector('[data-dashboard-cards]'); if(!cards) return; const items=appProducts(); const donations=JSON.parse(localStorage.getItem(donationKey)||'[]'); const contacts=JSON.parse(localStorage.getItem(contactKey)||'[]'); const sold=items.filter(p=>p.status==='Sold'); const available=items.filter(p=>p.status==='Available'); const reserved=items.filter(p=>p.status==='Reserved'); const value=available.reduce((s,p)=>s+Number(p.price||0),0); const data=[['Total inventory',items.length],['Available items',available.length],['Reserved items',reserved.length],['Sold items',sold.length],['Estimated inventory value',money(value)],['Donation requests',donations.length],['Customer requests',contacts.length + getBag().length],['Rewards members','Preview'],['Low inventory categories','Static preview']]; cards.innerHTML=data.map(([k,v])=>`<article class="dashboard-card"><span>${k}</span><strong>${v}</strong></article>`).join(''); }
function nextSku(cat){ const prefixes={'Little Gems':'LG','Home Treasures':'HOME','Bags':'BAG','Shoes':'SHOE','Accessories':'ACC','Men':'MEN','Women':'WOM'}; const prefix=prefixes[cat]||'TT'; const nums=appProducts().filter(p=>p.sku.startsWith(prefix+'-')).map(p=>Number(p.sku.split('-')[1])||0); return `${prefix}-${String(Math.max(0,...nums)+1).padStart(3,'0')}`; }
function renderInventory(){ const form=document.querySelector('[data-inventory-form]'); const table=document.querySelector('[data-inventory-table]'); if(!form||!table) return; const q=(document.querySelector('[data-inventory-search]')?.value||'').toLowerCase(); const status=document.querySelector('[data-inventory-status]')?.value||'All Statuses'; const items=appProducts(); const filtered=items.filter(p=>(status==='All Statuses'||p.status===status) && [p.sku,p.title,p.category,p.condition,p.status,p.brand].join(' ').toLowerCase().includes(q)); table.innerHTML=filtered.map((p)=>`<tr><td>${p.sku}</td><td>${p.title}</td><td>${p.category}</td><td>${p.condition}</td><td>${p.status}</td><td>${money(p.price)}</td></tr>`).join(''); document.querySelector('[data-inventory-summary]').textContent=`${items.length} items • ${items.filter(p=>p.status==='Sold').length} sold • ${money(items.reduce((s,p)=>s+Number(p.price||0),0))} listed value`; }
function setupInventory(){ const form=document.querySelector('[data-inventory-form]'); if(!form) return; const cat=form.querySelector('[name="category"]'); const sku=form.querySelector('[name="sku"]'); const price=form.querySelector('[name="price"]'); const cost=form.querySelector('[name="cost"]'); const profit=document.querySelector('[data-profit]'); const update=()=>{ if(!sku.value) sku.value=nextSku(cat.value); profit.textContent=money(Number(price.value||0)-Number(cost.value||0)); }; cat.addEventListener('change',()=>{sku.value=nextSku(cat.value); update();}); price.addEventListener('input', update); cost.addEventListener('input', update); update(); form.addEventListener('submit',(e)=>{ e.preventDefault(); const item=Object.fromEntries(new FormData(form).entries()); item.price=Number(item.price||0); item.cost=Number(item.cost||0); item.image=item.image||item.photo||'◇'; item.description=item.description||item.notes||''; item.hiddenGem=item.hiddenGem==='on'; item.clearance=item.clearance==='on'; const items=appProducts().filter(p=>p.sku!==item.sku); items.push(item); saveProducts(items); form.reset(); sku.value=''; update(); renderInventory(); renderShop(); renderAdmin(); }); }
function setupForms(){ document.querySelectorAll('[data-save-form]').forEach((form)=>form.addEventListener('submit',(e)=>{e.preventDefault(); const key=form.dataset.saveForm; const items=JSON.parse(localStorage.getItem(key)||'[]'); items.push(Object.fromEntries(new FormData(form).entries())); localStorage.setItem(key,JSON.stringify(items)); form.reset(); form.querySelector('[data-form-status]').textContent='Saved in this browser preview.';})); }
document.addEventListener('DOMContentLoaded',()=>{ updateBagCount(); renderCategoryHub(); renderShop(); renderProductDetail(); renderBag(); renderAdmin(); renderInventory(); setupInventory(); setupForms(); document.querySelectorAll('[data-search],[data-filter]').forEach(el=>el.addEventListener('input',renderShop)); document.querySelectorAll('[data-inventory-search],[data-inventory-status]').forEach(el=>el.addEventListener('input',renderInventory)); });
