import { readFileSync, existsSync } from 'node:fs';
const pages=['index.html','shop.html','women.html','men.html','little-gems.html','shoes.html','bags.html','accessories.html','home-treasures.html','hidden-gems.html','clearance.html','donations.html','promise.html','rewards.html','about.html','contact.html','policies.html','styles.css','manifest.json','README.md'];
const missing=pages.filter((p)=>!existsSync(p) && !existsSync(`src/${p}`));
if(missing.length) throw new Error(`Missing required files: ${missing.join(', ')}`);
const officialLogos=['assets/logos/main/treasured-twice-official.jpeg','assets/logos/little-gems/little-gems-official.png'];
const missingLogos=officialLogos.filter((p)=>!existsSync(p));
if(missingLogos.length) throw new Error(`Missing official logos: ${missingLogos.join(', ')}`);
const publicHtml=pages.filter(p=>p.endsWith('.html')).map(p=>readFileSync(p,'utf8')).join('\n');
const all=pages.map(p=>readFileSync(p,'utf8')).join('\n');
const required=['Treasured Twice','Once Loved, Treasured Again.','Hidden Gems','hello@shoptreasuredtwice.com','Clean Gem Promise','Little Gems','Treasure Chest Rewards'];
const absent=required.filter(t=>!all.includes(t));
if(absent.length) throw new Error(`Missing content: ${absent.join(', ')}`);
const forbidden=['Fresh Finds','fresh finds','Once loved. Treasured again.','Admin / Inventory Manager','Inventory Manager','href="admin.html"','href="inventory.html"','data-product-grid','data-inventory-form','Saved Request Bag','Warm Resale '+String.fromCharCode(66,111,117,116,105,113,117,101),'warm resale '+String.fromCharCode(98,111,117,116,105,113,117,101)];
const present=forbidden.filter(t=>all.includes(t));
if(present.length) throw new Error(`Forbidden content found: ${present.join(', ')}`);
const pagesMissingMainLogo=pages.filter(p=>p.endsWith('.html')&&!readFileSync(p,'utf8').includes('assets/logos/main/treasured-twice-official.jpeg'));
if(pagesMissingMainLogo.length) throw new Error(`Pages missing official main logo: ${pagesMissingMainLogo.join(', ')}`);
if(!readFileSync('little-gems.html','utf8').includes('assets/logos/little-gems/little-gems-official.png')) throw new Error('Little Gems page is missing its official logo');
const forbiddenFiles=['admin.html','inventory.html','product.html','products.js','script.js'];
const exposed=forbiddenFiles.filter(existsSync);
if(exposed.length) throw new Error(`Public inventory/admin preview files should not exist: ${exposed.join(', ')}`);
const hrefs=[...publicHtml.matchAll(/href="([^"]+)"/g)].map(m=>m[1]).filter(h=>!h.startsWith('#')&&!h.startsWith('mailto:')&&!h.startsWith('http'));
const broken=hrefs.filter(h=>!existsSync(h));
if(broken.length) throw new Error(`Broken links: ${[...new Set(broken)].join(', ')}`);
console.log('Static site QA check passed.');
